before:
  hooks:
    - go mod tidy

builds:
- binary: '{{ .ProjectName }}'
  main: main.go

  goos:
    - windows
    - linux
    - darwin
  goarch:
    - amd64
    - 386
    - arm
    - arm64

  ignore:
    - goos: darwin
      goarch: '386'
    - goos: windows
      goarch: 'arm'
    - goos: windows
      goarch: 'arm64'

archives:
- format: zip
  replacements:
      darwin: macOS

checksum:
  algorithm: sha256
