blank_issues_enabled: false

contact_links:
  - name: Ask an question / advise on using openrisk
    url: https://github.com/projectdiscovery/openrisk/discussions/categories/q-a
    about: Ask a question or request support for using openrisk

  - name: Share idea / feature to discuss for openrisk
    url: https://github.com/projectdiscovery/openrisk/discussions/categories/ideas
    about: Share idea / feature to discuss for openrisk

  - name: Connect with PD Team (Discord)
    url: https://discord.gg/projectdiscovery
    about: Connect with PD Team for direct communication