name: 🔨 Build Test
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Test Builds
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.x

      - name: Check out code
        uses: actions/checkout@v5

      - name: Build
        run: go build .
        working-directory: cmd/openrisk

      - name: Test
        run: go test ./...
        working-directory: cmd/openrisk

      - name: Building example
        # env:
        #   OPENAI_API_KEY: ${{secrets.OPENAI_API_KEY}}
        run: go build .
        working-directory: examples/

      
